version: '3.8'
services:
    nginx:
        image: nginx:latest
        container_name: welcome-nginx
        volumes:
            - "./:/var/www/html"
            - "./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "80:80"
        depends_on:
            - php
        networks:
            - backend

    php:
        build:
            context: "./docker/php"
        container_name: welcome-php
        volumes:
            - "./:/var/www/html"
            - "./docker/php/php.ini:/usr/local/etc/php/php.ini"
        networks:
            - backend

    database:
        image: mysql:5.7.39
        container_name: welcome-database
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=welcome
        ports:
            - "3306:3306"
        restart: always
        networks:
            - backend

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: welcome-phpmyadmin
        environment:
            - PMA_HOST=database
            - PMA_USER=root
            - PMA_PASSWORD=root
        ports:
            - "8080:80"
        restart: always
        links:
            - database
        depends_on:
            - database
        networks:
            - backend

networks:
    backend:
        driver: bridge
